# -*- coding: utf-8 -*-
"""Lista de Exercícios #03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LvE8j6Zfjs0-P9mEYJUH3hPbduKSJq1i

## Lista de Exercício 03

O objetivo dessa lista de exercícios é que você analise seu próprio conjunto de dados.

As dúvidas podem ser tiradas por email e também pelos comentários da aula. 

Mas priorize sempre a comunidade no Facebook e no Telegram. Além de você estar tirando sua dúvida, pode estar contribuindo com alguém.

Abuse da imaginação!

Importe o conjunto de dados "cars_unclean.csv" e inspecione. Em seguida, limpe o conjunto de dados:

* Identifique os dados inconsistentens;
* Cada coluna/feature deve ter o tipo de dado apropriado;
* Identifique os dados faltantes (missing values);
* Identifique as duplicatas;
* Limpe as colunas, deixando os elementos no formato correto;
* Identique os outliers
* Salve e exporte um novo conjunto de dados (csv) com o nome "cars_clean.csv"
"""

